- name: writing .pgpass
  shell: "echo *:*:*:*:{{ item.value.PASSWORD }} > {{ PGPASSFILE }}"

- file:
    mode: 0600
    path: ~/.pgpass
    state: file

- name: "dumping {{ item.key }} base"
  shell: "pg_dump --format=c --host={{ item.value.HOST }} --user={{ item.value.USER }} {{ item.value.NAME }} > {{ modoboa_ab_file }}{{ inventory_hostname }}-{{ item.key }}.sql"

- name: deleting .pgpass
  file:
    state: absent
    path: ~/.pgpass
