- name: retrieving DB credentials 1/2
  shell: /srv/modoboa/env/bin/python2 -c "import json; from instance.settings import DATABASES; print json.dumps(DATABASES)"
  args:
    chdir: /srv/modoboa/instance/
  become: true
  register: db_credentials_raw

- name: retrieving DB credentials 2/2
  set_fact:
    db_credentials: "{{ db_credentials_raw.stdout | from_json }}"

- name: creating dump directory
  file:
    state: directory
    mode: 0777
    path: "{{ modoboa_ab_dump_dir }}"

- archive:
    path: /srv/vmail
    dest: "{{ modoboa_ab_file }}{{ inventory_hostname }}-vmail_data.tgz"
    owner: "{{ ansible_user_id }}"

- include: "dump-{{ item.value.ENGINE.split('.')[-1] }}-base.yml"
  with_dict: "{{ db_credentials }}"

- name: "removing {{ modoboa_dump_dir }} if specified"
  file:
    path: "{{ modoboa_ab_dump_dir }}"
    state: absent
  when: modoboa_ab_remove_after
